// flow-typed signature: fb8ed345bf4dfdd2152d6480a6865c42
// flow-typed version: <<STUB>>/rx-binder_v^4.0.8/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rx-binder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rx-binder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rx-binder/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rx-binder/lib/index' {
  declare module.exports: $Exports<'rx-binder/lib'>;
}
declare module 'rx-binder/lib/index.js' {
  declare module.exports: $Exports<'rx-binder/lib'>;
}
