// flow-typed signature: b1b079bee4359062912d0e9b51381d7b
// flow-typed version: <<STUB>>/rx-jupyter_v^5.5.14/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rx-jupyter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rx-jupyter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rx-jupyter/lib/base' {
  declare module.exports: any;
}

declare module 'rx-jupyter/lib/bookstore' {
  declare module.exports: any;
}

declare module 'rx-jupyter/lib/contents' {
  declare module.exports: any;
}

declare module 'rx-jupyter/lib' {
  declare module.exports: any;
}

declare module 'rx-jupyter/lib/kernels' {
  declare module.exports: any;
}

declare module 'rx-jupyter/lib/kernelspecs' {
  declare module.exports: any;
}

declare module 'rx-jupyter/lib/sessions' {
  declare module.exports: any;
}

declare module 'rx-jupyter/lib/terminals' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rx-jupyter/lib/base.js' {
  declare module.exports: $Exports<'rx-jupyter/lib/base'>;
}
declare module 'rx-jupyter/lib/bookstore.js' {
  declare module.exports: $Exports<'rx-jupyter/lib/bookstore'>;
}
declare module 'rx-jupyter/lib/contents.js' {
  declare module.exports: $Exports<'rx-jupyter/lib/contents'>;
}
declare module 'rx-jupyter/lib/index' {
  declare module.exports: $Exports<'rx-jupyter/lib'>;
}
declare module 'rx-jupyter/lib/index.js' {
  declare module.exports: $Exports<'rx-jupyter/lib'>;
}
declare module 'rx-jupyter/lib/kernels.js' {
  declare module.exports: $Exports<'rx-jupyter/lib/kernels'>;
}
declare module 'rx-jupyter/lib/kernelspecs.js' {
  declare module.exports: $Exports<'rx-jupyter/lib/kernelspecs'>;
}
declare module 'rx-jupyter/lib/sessions.js' {
  declare module.exports: $Exports<'rx-jupyter/lib/sessions'>;
}
declare module 'rx-jupyter/lib/terminals.js' {
  declare module.exports: $Exports<'rx-jupyter/lib/terminals'>;
}
