// flow-typed signature: f00ca2344026594316f27e48ed8c0b80
// flow-typed version: <<STUB>>/@nteract/display-area_v^5.0.4-alpha.0/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nteract/display-area'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nteract/display-area' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nteract/display-area/lib/display' {
  declare module.exports: any;
}

declare module '@nteract/display-area/lib' {
  declare module.exports: any;
}

declare module '@nteract/display-area/lib/output' {
  declare module.exports: any;
}

declare module '@nteract/display-area/lib/richest-mime' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nteract/display-area/lib/display.js' {
  declare module.exports: $Exports<'@nteract/display-area/lib/display'>;
}
declare module '@nteract/display-area/lib/index' {
  declare module.exports: $Exports<'@nteract/display-area/lib'>;
}
declare module '@nteract/display-area/lib/index.js' {
  declare module.exports: $Exports<'@nteract/display-area/lib'>;
}
declare module '@nteract/display-area/lib/output.js' {
  declare module.exports: $Exports<'@nteract/display-area/lib/output'>;
}
declare module '@nteract/display-area/lib/richest-mime.js' {
  declare module.exports: $Exports<'@nteract/display-area/lib/richest-mime'>;
}
