// flow-typed signature: b39b16fbfbbc66611f10334fd16b789c
// flow-typed version: <<STUB>>/@nteract/messaging_v^7.0.12/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nteract/messaging'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nteract/messaging' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nteract/messaging/lib' {
  declare module.exports: any;
}

declare module '@nteract/messaging/lib/messages' {
  declare module.exports: any;
}

declare module '@nteract/messaging/lib/types' {
  declare module.exports: any;
}

declare module '@nteract/messaging/lib/wire-protocol' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nteract/messaging/lib/index' {
  declare module.exports: $Exports<'@nteract/messaging/lib'>;
}
declare module '@nteract/messaging/lib/index.js' {
  declare module.exports: $Exports<'@nteract/messaging/lib'>;
}
declare module '@nteract/messaging/lib/messages.js' {
  declare module.exports: $Exports<'@nteract/messaging/lib/messages'>;
}
declare module '@nteract/messaging/lib/types.js' {
  declare module.exports: $Exports<'@nteract/messaging/lib/types'>;
}
declare module '@nteract/messaging/lib/wire-protocol.js' {
  declare module.exports: $Exports<'@nteract/messaging/lib/wire-protocol'>;
}
