// flow-typed signature: faaf8410e534e23c765bec2858694031
// flow-typed version: <<STUB>>/@nteract/presentational-components_v^3.4.4/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nteract/presentational-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nteract/presentational-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nteract/presentational-components/lib/components/cell' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/CellMenu/CellMenu' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/CellMenu' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/cells' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/CircularButton/CircularButton' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/CircularButton' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/CircularButton/ProgressRing' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/command-palette/command-button-row' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/command-palette/command-palette' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/command-palette' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/command-palette/key-tag' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/error' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/icons' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/icons/icons' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/icons' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/input' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/outputs' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/pagers' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/prompt' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/sidebar' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/sidebar/sidebar-item' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/sidebar/sidebar' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/source' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/ToggleSwitch/ToggleSwitch' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/toolbar/Icons' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/toolbar' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/toolbar/toolbar-item' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/components/toolbar/toolbar' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/styles' {
  declare module.exports: any;
}

declare module '@nteract/presentational-components/lib/syntax-highlighter' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nteract/presentational-components/lib/components/cell.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/cell'>;
}
declare module '@nteract/presentational-components/lib/components/CellMenu/CellMenu.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/CellMenu/CellMenu'>;
}
declare module '@nteract/presentational-components/lib/components/CellMenu/index' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/CellMenu'>;
}
declare module '@nteract/presentational-components/lib/components/CellMenu/index.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/CellMenu'>;
}
declare module '@nteract/presentational-components/lib/components/cells.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/cells'>;
}
declare module '@nteract/presentational-components/lib/components/CircularButton/CircularButton.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/CircularButton/CircularButton'>;
}
declare module '@nteract/presentational-components/lib/components/CircularButton/index' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/CircularButton'>;
}
declare module '@nteract/presentational-components/lib/components/CircularButton/index.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/CircularButton'>;
}
declare module '@nteract/presentational-components/lib/components/CircularButton/ProgressRing.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/CircularButton/ProgressRing'>;
}
declare module '@nteract/presentational-components/lib/components/command-palette/command-button-row.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/command-palette/command-button-row'>;
}
declare module '@nteract/presentational-components/lib/components/command-palette/command-palette.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/command-palette/command-palette'>;
}
declare module '@nteract/presentational-components/lib/components/command-palette/index' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/command-palette'>;
}
declare module '@nteract/presentational-components/lib/components/command-palette/index.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/command-palette'>;
}
declare module '@nteract/presentational-components/lib/components/command-palette/key-tag.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/command-palette/key-tag'>;
}
declare module '@nteract/presentational-components/lib/components/error.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/error'>;
}
declare module '@nteract/presentational-components/lib/components/icons.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/icons'>;
}
declare module '@nteract/presentational-components/lib/components/icons/icons.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/icons/icons'>;
}
declare module '@nteract/presentational-components/lib/components/icons/index' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/icons'>;
}
declare module '@nteract/presentational-components/lib/components/icons/index.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/icons'>;
}
declare module '@nteract/presentational-components/lib/components/input.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/input'>;
}
declare module '@nteract/presentational-components/lib/components/outputs.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/outputs'>;
}
declare module '@nteract/presentational-components/lib/components/pagers.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/pagers'>;
}
declare module '@nteract/presentational-components/lib/components/prompt.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/prompt'>;
}
declare module '@nteract/presentational-components/lib/components/sidebar/index' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/sidebar'>;
}
declare module '@nteract/presentational-components/lib/components/sidebar/index.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/sidebar'>;
}
declare module '@nteract/presentational-components/lib/components/sidebar/sidebar-item.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/sidebar/sidebar-item'>;
}
declare module '@nteract/presentational-components/lib/components/sidebar/sidebar.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/sidebar/sidebar'>;
}
declare module '@nteract/presentational-components/lib/components/source.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/source'>;
}
declare module '@nteract/presentational-components/lib/components/ToggleSwitch/ToggleSwitch.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/ToggleSwitch/ToggleSwitch'>;
}
declare module '@nteract/presentational-components/lib/components/toolbar/Icons.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/toolbar/Icons'>;
}
declare module '@nteract/presentational-components/lib/components/toolbar/index' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/toolbar'>;
}
declare module '@nteract/presentational-components/lib/components/toolbar/index.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/toolbar'>;
}
declare module '@nteract/presentational-components/lib/components/toolbar/toolbar-item.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/toolbar/toolbar-item'>;
}
declare module '@nteract/presentational-components/lib/components/toolbar/toolbar.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/components/toolbar/toolbar'>;
}
declare module '@nteract/presentational-components/lib/index' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib'>;
}
declare module '@nteract/presentational-components/lib/index.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib'>;
}
declare module '@nteract/presentational-components/lib/styles.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/styles'>;
}
declare module '@nteract/presentational-components/lib/syntax-highlighter/index' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/syntax-highlighter'>;
}
declare module '@nteract/presentational-components/lib/syntax-highlighter/index.js' {
  declare module.exports: $Exports<'@nteract/presentational-components/lib/syntax-highlighter'>;
}
